import Footer from '@/layouts/Footer';
import Header from '@/layouts/Header';
import Head from 'next/head';
import Image from 'next/image';
import React, { useEffect, useState } from 'react';

const CheckOutSuccess = () => {
  const [isProcessing, setIsProcessing] = useState(true);

  useEffect(() => {

    const delay = setTimeout(() => {
      setIsProcessing(false);
    }, 10000);

    return () => clearTimeout(delay);
  }, []);

  useEffect(() => {

  }, [isProcessing]);


  return (
    <div>
      <Head>
        <title>Processing Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="order-success" style={{
        fontFamily: 'Arial, sans-serif;',
        textAlign: 'center',
        padding: '50px'
      }}>
        <h1>Đơn hàng của bạn đang được xác nhận!</h1> <Image src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBUSEhYSEhESFRIRGBkSEhIYEhgVFhgQGRQdGhgWFhYdIS8lHB4rIBgaJkYmKy8xNTU1HCQ7TjszPy40NTEBDAwMEA8QHhISHzQsJSg0Nj8xNTYxPzYxNjQ0NDQ0NDQ0ND03NDE0NDY0NjQ0PTQ0NDQ2NDQ2NDQ0NDExNDQ0NP/AABEIAOEA4QMBIgACEQEDEQH/xAAcAAEAAQUBAQAAAAAAAAAAAAAABgEDBAUHAgj/xABNEAACAQMCAwMFCAwMBwAAAAABAgADBBEFIQYSMRNBUQcUImFxMlKBkZKTsdEXNUJEcnOCoaKzwdIVFiMkM0VTVGKEsrQ0ZHSDlNPh/8QAGQEBAAMBAQAAAAAAAAAAAAAAAAECAwQF/8QAKhEBAQACAQQBAwMEAwAAAAAAAAECEQMEEiExUSJBoQUTgRRhkcEVUnH/2gAMAwEAAhEDEQA/AOzREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQERECkTW3muW1BuWtdW9NhvyvWRGx+CTmYh4w08f1hafPp9cjadVvYkfPGmnD7/tvnRKfx207+/2/zgjcO2/CQxI+ONNO/v8AbfOAT2OMNPP9YWvz6D9sbh234b2Jpk4psW6X9mf8zT/em1o1VdQyMrK24ZSGUjxBHWSWWLsREIIiICIiAiIgIiICIiAiIgIiICIiAiIgUmo4qvWt7G5rocPSpO6Hrh+U8px7cTbiRnyifaq6/F4+NlkX0me45jpGkWFPTl1LUhcVql1VdVRHYMWDuCSeZck8jMWZvDv63dKuNCrV6dEaddKazrTDPWcqGZgq83LVJxkgdO+WOIttA0weNSoT7c1PrkY4Z/460/6q3/XpM96sjqk3Ld37p7xKNG0+4Ns+m1ajqqszLVcKOYZAy1TJOMfHMvhK00bUWqomnPTNFQ7c9VyCpJGQVqHpj88ivlW+2tX8Cl+rE2/kZ/p7v8Qv+oxL9Wle36O7d2wTrehnppNzjuIrEZHccdrtJnoPB+k39slzTtHVKvNhWr1QwKsUYHFQjqpnEafuR7B9E+gPJT9qbf21v9xUjHzTllxm5atv5MdNPShUHsuKv7WkV4U1Ono+o3dhXuCtovpUy+SBUwjLsowGKOc4AB5BOvzS6rw3aXBd61pQeq4wajU1LnAwPSxnYY+KXs+GMzt8Vn2F9TuKa1aNRKlNvcurBlODg7jvBBEy5zTyIVCbKspOeWvkermo08/ROlyZdxXKatisRElBERAREQEREBERAREQEREBERAREQKSO8fJzaZdjwou3yfS/ZJFMTVbFbihVoOSEr03pMR1CupUkeveEzxduJ60ebh2wbG1O4qKT3D0qwGT3dBIxwwc31pjf+dW/wCvST/TbbWNMR7RLGld23OWUkBlOTklfTBAJ3wQcEmZFPXtQpsH/i6gcdHWiQw9jKpImenTMtSya/yi/lV+2tX8Cl+rE23kZ/p7v8Qv+ozMvuJLmuwe44X7ZwOUM9tUchfAM1E7bmXLDiu5tubzfhl6PPjm7OhVp82OnNy0BnGTEnnau729uvy5PT9yPYPon0B5KvtTb+2t/uKkhjaw7EseEkLMSSTZuSSdySfN9zNlbcZakiKlLQHREHKqCnWRQPAL2YAEYzVOS3Ka1+XUZBeIPKCtvc1bOnZ169WkBkpgjLIr5CgFsDnUZx1mubizW39xo6r+GGP0uszeAuHLmncV9Rv8Lc3I5BTBBKqWBPNy5A9ygABOAu+8vvfplMZj5p5I9Hq21k5r02Rq1TnVGBVuzCKoLKd1yVOx7sSfxESaVyu7tWIiSgiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgUlYiBSJWICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiBSc31zj+4N09rplslfzfarVfJUuDhlUBlAAO2SdyDgYGTLeMNTNpYXFdTh0QimfCq55EPymE5PwnpdxURbe1q9lUNFr6rUKhud2blt6LE9AQCx9pMy5MrJrH234cMbvLL1E34a8oSV6otrykbW5JCqGJ5HY7BQSAVY9wOx7iTtJ3OPVLVNVswzoEuE5kJxulwmzIf8ACTg8vgfETL4e8owtbYUL9a73FBuyBQKzMoyBzszD0hggnO+AeuZnw8/fuZeLPa/Nwdurj6rq2JD+MuNlsCtClT7e7qYKUgThQehcjJye5RufV1mnfysUNwtpc5x6JJpgZxtnDZ+LJkT0lqiZvqiCvqGoVCtshO2GOC3qXoPUvKNsmX5OXWP0+bfSvFwW36vEiXaL5RmFdbfUrcWzPjkqgnkyenMD0HdzAkeOJ0UTkdxR/hClWtbmmtK7tjgjPMFcj0XQ96Njp4fAZZ0Djy7t7cWfmbXFe3Jp8/aMSFBwFdVQklcFdyMgCU4ue3cz8We1+Xg1q4eq7JE5FU1vXLn3PY2qnphVBx+Vzt+YSx/F+9qMGuNVrt0JQNUKezHOox+TJy6rix+6uPS512PmlczjjcGKQR53Xycel3jHhvPCaBf0PStdVrZHRHZ+X4QWZf0ZSdbxW+1v6TN2aJyqx48vbRgmp24dCeUV6YCsfXgegx9XoH1HpOjaTqlG6pLWt6i1KbdGHce8MOoI8DvOjHLHKblc+WGWHtsIiUl1FYiICIiAiIgIiICIiAiIgIiUgQjyusRpbgfdVKQPzgP7Jz/Q6t1WZ1snNCg9OhQqXJXDhaNPlK0znqSzHbB6br3yLyhXrX19T0umSKVLFa6YeOMhT7FI/KceE29tbrTRadNQqIOVVHQCed1nUft3U9vR6Xi7sfPpjaRpaWtM00LtzMXd2bmZnIALE/kiZItkDFwiB2903IOY+1sZMuxPIvJlbba7+2MHWbDzmi1HnKByuWAyeUMCR19XWWOGaSPq1RXKq1nQp07SidvRZTz1FB64B5du5vVNqJrtV0hLjlYs9OtTOaVdG5aiN6m7x6p09N1Ewynd6Zc3F3Y2T2rxPS7HVraoBgXdKpRfHQtT5XBPrxgfBNOx7DVlUbJe0ySO41EHX24T9OZRsb2rcW73VzSrU7QuyOKfJVYuvLhgPR7hv9MxeIxi+09h153X4DyZ/MTN+Tkwz5Ppu5Zf9suPDLHD6vtUojErE83udWnnET1EbpparUldSjqrIwwysMgj1iRDNTRLkXNvzNZ1WCV6JOcDuGT3jflY+w9d5nLF7arWpvScZR1Kt8PePWDv8E6On6jLjynx91OTixyx1WrXVtT1lm8zbzOxViorHao+NjhhuT6kIA6FiZe+xxWxzfwxedp7/L4z7O0z+lM7yXX7Na1LSof5WwqNSP4sklDjwyHA9SiSW51UIeVVLEbE5wM+2ezny44zuteZ2Zd1xxiCVdQ1XRiGuWF9ZAgNUye0RemSx9JT+FzL3ZGZ0bRtVpXdFbig3NTcbdxBGxVh3EHbExaF8lbNN0HpgqVbDKykbqfHbukH4ZzpWr1NOyfNL0drbZJPK2DgZ8fQdPXypL8XLM5vG7imeFnizVdTiImzAiIgIiICIiAiIgUnknAye6epD+POKxY01o017S6uQUo0tzjPo87AbncgBRux28SIt0mTd0iPAdDzrz7UWJ5qtchc+8/pCPVs6D8kSTTG4K4Wr2tmtKqQjOxqvTB5sMQoAJGxIVV6ZGZtrjS3QZADAeHX4p4vWcWWWfdJXq8HJjjO22f2WrC0NViM4C7k4z7JkXelFFLK2Qu5BGDjxmsOqLbEM9VKfMeUczBQx8BnrMy+1g9mxdkRAMsxOAF9ZJwBMuOcX7espd/ZbP8Ad7942aY0S1b11dQ6OrI26srBlI9REuzks06SYlzYJUelUYEvQLNTOcAFlwcjvmXEmZWeYWbIiJCSIiAiIgRjTNQFpf6o+/L5ulfA6llCjb15c/HMPTdEe/pi5vK9X+VHNTpI/IqIfcnGD3b+zrkzDudPq3d/fLSrCmvIlKoSnMHTlXKer0kzt4ScWVv2dNKQORSRUBxjIVQM4+Cejzc3Zx4yXzqfx4cuGG87b6V0+j2CIgd27PADs3MxwduY9/hNf5Tx2dxptyuz07gLnxXnR8fon5Rm5oUyzqB90fzd80vGjed6vYWNPfsHFxXxuFHMr4PgeRD8tZp+n91lt+WPVamU/wDK6hERPWeaREQEREBERAREQKTkd1TqXGtai9M5uLW1dbMbZWr2SKhTO2cu/XvedcnLuKX/AIN1qjqDDFveJ2Fd8e5YAKSfYFpt6wjSuXpfj9uS1qruxao7s+fSZ2ZnyDvktvnMk/k/vbw39CnQq1ShYGtTLs1PzcEdozKTgbbA++I8ZOPKLw1Tq9hc0bXndrimtyaSnmqW7bFm5evcObqM9ZMtI0a3tEKW1FKan3XLksxHQs5yzH2kzLTe5y4+kf434MW/VWRuSqmSpxlTzY5gRnvwPi9oMA+x/qDEU6lQdkp9EdpUdVA6FUK4/OJ2+MSlw+DHlsmr5Q/ROGmtqK0UGy5JZmALMTlmwOm/dMm4tHTdl28Qcj4x0konl0BBBGQdiPVOXk6LHLd3dtcerzl9TSJSkuXFPlYr4EgezulsTycpZbK9LG7m4rMG41e3psUe4oq69UaooYbZ3GdpnTCudKt6hLVLei7HqzU1LHbG7YzLYdm/q3/CLv7L1tdJUGadRHHeUdXHw4MvTWXPAFCtT7ayLWt0meVkduzLjuKk+iD/AIcYz0PSWOF9Ue4pMtZeW4t3NGsMAekvfgbA7Ebd6nunRzdN24TPG7lZcfNMrcb7jdTF1O+S2pNWc+igzjvZvuVHrJ2mXNNe6Ete4WrXdqlKngpbFcUww6s2/pZ8NvDcbTDimNy+u+GuduvCJcIa8lB6huuZDdsKq1irBWOWyOnuctsdx1k/pXdJl5xcW/J15zXQLjxyWknuLKjdUOzrU0ek6j0GGQNtseBHiMETk1jwjb09ZOn3Ku9Kqhe1YOVbGCyhyOuyOvtUHvnrZ9Jx8l7t3y4Mepyks+Egv+NaFD+RsP55e1PQp8gZqasfA/d+OF223Im74B4VqWvaXd4ee+ud6hJDFFJyU5hsSSATjbYAbDJkGjcO2tmCLa3SmSMMwBLkeDOxLH4TNtOzj4scJqOPk5blv+6sRE1ZEREBERAREQERECk1evaNSvaD29ZSUfcEbMrj3Loe4g/V0M2spB6clttRvdB/kLuk1zYKcUrhOqJ3DJ2X8BiMdzEDEluncc6fXAK3dNCfuKp7JgfD08A/ASJKmUEYIBB2IO+RI5qHAun1yS9nTVjuWplqJJ8T2ZGfhlLj8NJnL7bFNVoN7m5oN7KyH6DLou6Z6VaZ/LX65FKvkp05uiVl9lYn/UDLDeSKwPR7oflp+1JHbU7x+U0Fwv8AaJ8oSlS5RQSaiADcnmEhf2ILD3918un/AOuB5IbD3918un+5I7Kbx+WXcXKszNzL6RJ6jp3S32y+/X5QloeSOw9/dfOJ+5K/Yk0/31z84v7k4Mv07d3cvw7Z1uMmpHo3Kf2lP5a/XKG9pjrVp/LX65X7E2nf8x86P3Z7Hkp073tf57/5I/4yf9vwn+unw9PxfZWdAmpcI9TduxpMKjlsbL6Oy9OrECRHhK8QecXVetQp1Lyq1bkNVAVUsxGQT4u3wASXjyW6cPuKx/77/snseTHTf7Cof8xV/Y06sum7uOce9Rz4c+OOVy+9attctR1urf55PrltuIrQffVH4HB+ibxfJnpg+9W/8iv+/LyeTzTB95qfbVqt9Lznn6bj81teunw168f6dRpgG55mVd1SnUffvHNy8vxmajhoVNV1ZdT7F6VpbIadEt1duV1GO471HJxkDCjJ3k0teELCmQyWNsGG4Y0lYg+ILZm8VQBgDAGwHqnfjx9sk+HFlyS7193uIiaMyIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiIH/2Q==" width="800"
          height="500"
          alt="Image" />
        {isProcessing ? (
          <h3>Vui lòng đợi đang được xử lí...</h3>
        ) : (
          <h3>Đã xử lí thành công! Cảm ơn bạn đã đặt hàng!</h3>
        )}
      </div>

      <Footer />
    </div>
  );
}

export default CheckOutSuccess;